name: CI-CD-Sucesso

on:
  push:
    branches: [ "projeto-aula" ]
  pull_request:
    branches: [ "projeto-aula" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Build do Projeto
      run: echo "Compilando e preparando o código..."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy simulado
      run: echo "Enviando para o servidor de produção!"

name: Testes Unitarios

on: [push, pull_request]

jobs:
  executar-testes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configurar Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Rodar Testes Unitarios
      run: python -m unittest test_main.py
